spring:
  config:
    activate:
      on-profile: local


  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.hbghiqwugsyofztmepbn
    password: "Scrum491@GymBros"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: leoyegh@gmail.com
    password: "aclg lrsu owpu tdkh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
