spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://db.hbghiqwugsyofztmepbn.supabase.co:5432/postgres?user=postgres&password=Scrum491@GymBros
    username: hbghiqwugsyofztmepbn           
    password: ""    
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: leoyegh@gmail.com
    password: "aclg lrsu owpu tdkh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
